# Generated by Django 5.1.4 on 2025-04-23 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=100)),
                ('staff_role', models.CharField(max_length=50)),
                ('staff_email', models.CharField(max_length=50)),
                ('time_off_allowance', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Schedule', serialize=False, to='staff_scheduling.staff')),
            ],
        ),
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('additional_info', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=20)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_requests', to='staff_scheduling.staff')),
            ],
        ),
    ]
