# Generated by Django 5.1.4 on 2025-03-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('shift_times', models.CharField(max_length=100)),
                ('hours_worked', models.FloatField(default=0)),
            ],
        ),
    ]
