# Generated by Django 5.1.4 on 2025-05-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
