# Generated by Django 5.1.4 on 2025-04-23 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('table_no', models.IntegerField()),
                ('max_capacity', models.IntegerField()),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('number_of_guests', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Fully Booked', 'Fully Booked')], default='Pending', max_length=20)),
                ('table_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.table')),
            ],
        ),
    ]
