# Generated by Django 5.1.4 on 2025-05-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
    ]
