# Generated by Django 5.1.4 on 2025-05-07 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_create_tables'),
    ]

    operations = [
    ]
