# Generated by Django 5.1.4 on 2025-05-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_table_available_alter_table_table_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_email',
            field=models.EmailField(max_length=100),
        ),
    ]
