# Generated by Django 5.1.4 on 2025-03-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity_on_hand', models.IntegerField()),
                ('reorder_level', models.IntegerField()),
                ('supplier_info', models.TextField()),
            ],
        ),
    ]
