# Generated by Django 5.1.4 on 2025-05-03 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_contact', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.menu')),
                ('stock_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
            options={
                'unique_together': {('menu_item_ID', 'stock_ID')},
            },
        ),
    ]
