# Generated by Django 5.1.4 on 2025-05-05 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(db_column='stock_id', primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_column='item_name', max_length=100)),
                ('quantity', models.IntegerField(db_column='quantity')),
                ('supplier_name', models.CharField(db_column='supplier_name', max_length=100)),
                ('supplier_contact', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'inventory_stock',
            },
        ),
        migrations.CreateModel(
            name='MenuIngredients',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('menu_item', models.ForeignKey(db_column='menu_item_ID_id', on_delete=django.db.models.deletion.CASCADE, to='orders.menu')),
                ('stock_item', models.ForeignKey(db_column='stock_ID_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
            options={
                'verbose_name': 'Menu Ingredient',
                'verbose_name_plural': 'Menu Ingredients',
                'db_table': 'Inventory_menu_ingredients',
                'unique_together': {('menu_item', 'stock_item')},
            },
        ),
    ]
