# Generated by Django 5.1.4 on 2025-05-05 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('staff_scheduling', '0002_alter_schedule_staff_id_alter_staff_staff_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allergens', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'orders_menu',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('special_requests', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('time_placed', models.DateTimeField(auto_now_add=True)),
                ('staff_ID', models.ForeignKey(db_column='staff_ID_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_scheduling.staff')),
                ('table_ID', models.ForeignKey(db_column='table_ID_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.table')),
            ],
            options={
                'db_table': 'orders_order',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_id', models.ForeignKey(db_column='menu_id', on_delete=django.db.models.deletion.CASCADE, to='orders.menu')),
                ('order_id', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'db_table': 'orders_order_items',
            },
        ),
    ]
