# Generated by Django 5.1.4 on 2025-04-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_supplier_remove_inventoryitem_supplier_info_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_ordered',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Served', 'Served')], default='Received', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='items_ordered',
            field=models.ManyToManyField(related_name='orders', to='inventory.inventoryitem'),
        ),
    ]
